//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka322mat.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academiki
    {
        public int Id { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Date_Birthday { get; set; }
        public string Specializaciya { get; set; }
        public Nullable<int> year_prisvoi { get; set; }
    }
}
