//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka322mat.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Exemp()
        {
            this.ListStudent = new HashSet<ListStudent>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Cod { get; set; }
        public Nullable<int> TabNumber { get; set; }
        public string Auditoriya { get; set; }
    
        public virtual Disciplina Disciplina { get; set; }
        public virtual Prepod Prepod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListStudent> ListStudent { get; set; }
    }
}
