//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka322mat.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListStudent
    {
        public int id { get; set; }
        public Nullable<int> id_exemp { get; set; }
        public Nullable<int> id_Student { get; set; }
        public Nullable<int> ochenka { get; set; }
    
        public virtual Exemp Exemp { get; set; }
        public virtual Student Student { get; set; }
    }
}
