//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace uchebka322mat.Components
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TehnikumshamatEntities2 : DbContext
    {
        public TehnikumshamatEntities2()
            : base("name=TehnikumshamatEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Academiki> Academiki { get; set; }
        public virtual DbSet<Cafedra> Cafedra { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Disciplina> Disciplina { get; set; }
        public virtual DbSet<Exemp> Exemp { get; set; }
        public virtual DbSet<Facultet> Facultet { get; set; }
        public virtual DbSet<Inshiner> Inshiner { get; set; }
        public virtual DbSet<ListStudent> ListStudent { get; set; }
        public virtual DbSet<Prepod> Prepod { get; set; }
        public virtual DbSet<Sotrudnik> Sotrudnik { get; set; }
        public virtual DbSet<Specialnost> Specialnost { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<ZavCafedra> ZavCafedra { get; set; }
        public virtual DbSet<Zayvka> Zayvka { get; set; }
        public virtual DbSet<Ученики> Ученики { get; set; }
    }
}
